version: '3'

networks:
  local:

services:
  build:
    image: hseeberger/scala-sbt:8u222_1.3.3_2.13.1
    working_dir: /app
    volumes:
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.sbt:/root/.sbt
      - $PWD:/app
    command: sbt ~package
    networks:
      local:

